variable "nsg_name" {}
variable "location" {}
variable "rg_name" {}
variable "security_rule_name" {}
variable "priority" {}
variable "direction" {}
variable "access" {}
variable "protocol" {}
variable "source_port_range" {}
variable "destination_port_range" {}
variable "source_address_prefix" {}
variable "destination_address_prefix" {}
